ci: test validate

diff --git a/.github/workflows/cko-preview.yml b/.github/workflows/cko-preview.yml
--- a/.github/workflows/cko-preview.yml
+++ b/.github/workflows/cko-preview.yml
@@ -31,8 +31,11 @@ jobs:
           CLIENT_SECRET: ${{ secrets.CKO_CLIENT_SECRET }}
           CONNECTOR_KEY: ${{ secrets.CKO_CONNECTOR_KEY }}
         run: |
-          echo "Updating connector to tag $GITHUB_REF_NAME"
+          TIMEOUT=600 # 10 minutes
+          START_TIME=$(date +%s  
           
+          echo "Updating connector to tag $GITHUB_REF_NAME"
+        
           echo "********************************"
           echo Authenticating with commercetools
           echo "********************************"
@@ -62,6 +65,15 @@ jobs:
 
           # Validate when the `isPreviewable` is done
           while true; do
+            # Calculate elapsed time
+            ELAPSED_TIME=$(($(date +%s) - START_TIME))
+
+            # Check if we've exceeded the timeout
+            if [ "$ELAPSED_TIME" -ge "$TIMEOUT" ]; then
+              echo "Timeout reached. Exiting with failure."
+              exit 1
+            fi
+            
             # Execute the curl request and capture the response
             RESPONSE=$(curl --silent --show-error --location "https://connect.europe-west1.gcp.commercetools.com/connectors/drafts/key=$CONNECTOR_KEY" \
               --header 'Content-Type: application/json' \
